services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./src/:/app/src

  mysql:
    image: mysql:latest
    ports:
      - "4000:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Fichier SQL pour l'initialisation
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - mysql
