services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src/:/app/src

  mysql:
    image: mysql:latest
    ports:
      - "4000:3306"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "5050:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
